Description: Infrastructure for wedding website

Parameters: 
    WebsiteDomain:
        Type: String
        Description: The root domain (e.g. cnn.com) of the website
    WebsiteHost:
        Type: String
        Description: The website host (e.g. www.cnn.com) for the website

Resources:
    # Route53 Hosted Zone to manage DNS records for our website
    # We assume this domain is used ONLY for website hosting.
    # Otherwise, you may already have DNS configured separately.
    HostedZone:
        Type: "AWS::Route53::HostedZone"
        Properties:
            Name: !Ref WebsiteDomain

    # We're hosting our website in an S3 bucket corresponding to our root domain
    WebsiteRootDomainBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref WebsiteDomain
            WebsiteConfiguration:
                IndexDocument: index.html

    # For this site, all requests to the website host redirect -> the root domain
    WebsiteHostBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref WebsiteHost
            WebsiteConfiguration:
                RedirectAllRequestsTo:
                    HostName: !Ref WebsiteDomain

    WebsiteCloudfrontLoggingBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Join ['-', [ !Ref WebsiteDomain, 'logs' ] ]

    WebsiteCloudfrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            Aliases:
                - !Ref WebsiteDomain
                - !Ref WebsiteHost
            DefaultCacheBehavior:
                ForwardedValues:
                    QueryString: false
                    Cookies:
                        Forward: "none"
                TargetOriginId: "website"
            DefaultRootObject: "index.html"
            Enabled: true
            Logging:
                Bucket: !Ref WebsiteCloudfrontLoggingBucket
            Origins:
                -
                    DomainName: !Ref WebsiteRootDomainBucket
                    Id: "website"
                    S3OriginConfig:
                        OriginAccessIdentity: "origin-access-identity/cloudfront/website-identity"
