Description: Resources for wedding website

Parameters: 
    WebsiteDomain:
        Type: String
        Description: The root domain (e.g. cnn.com) of the website
    WebsiteHost:
        Type: String
        Description: The website host (e.g. www.cnn.com) for the website

Resources:
    WebsiteRootDomainBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref WebsiteDomain
            WebsiteConfiguration:
                IndexDocument: index.html

    WebsiteHostBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref WebsiteHost
            WebsiteConfiguration:
                RedirectAllRequestsTo:
                    HostName: !Ref WebsiteDomain

    WebsiteCloudfrontLoggingBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Join ['-', [ !Ref WebsiteDomain, 'logs' ] ]

    WebsiteCloudfrontDistribution:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            Aliases:
                - !Ref WebsiteDomain
                - !Ref WebsiteHost
            DefaultCacheBehavior:
                ForwardedValues:
                    QueryString: false
                    Cookies:
                        Forward: "none"
                TargetOriginId: "website"
            DefaultRootObject: "index.html"
            Enabled: true
            Logging:
                Bucket: !Ref WebsiteCloudfrontLoggingBucket
            Origins:
                -
                    DomainName: !Ref WebsiteRootDomainBucket
                    Id: "website"
                    S3OriginConfig:
                        OriginAccessIdentity: "origin-access-identity/cloudfront/website-identity"


